container_build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - "[ -n \"$APPSETTINGS\" ] && cat $APPSETTINGS > appsettings.json"
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build --pull --tag $CI_REGISTRY_IMAGE:latest .
    - podman push $CI_REGISTRY_IMAGE:latest
    
upload_uploads_folder:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - podman run --rm -v /ibrahim.sertkaya82/muafiyetprojesiv1/wwwroot/uploads:/uploads alpine sh -c "cp -r /uploads/* /ibrahim.sertkaya82/muafiyetprojesiv1/wwwroot/uploads/"
  dependencies:
    - container_build

deploy_production:
  stage: deploy
  needs:
    - container_build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
    - podman pull $CI_REGISTRY_IMAGE --creds=$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
    - systemctl restart container-uygulamav1.service

